s = (input('Digite algo: '))
print('É um número ?')
print(s.isnumeric())
print('É uma letra ?')
print(s.isalpha())
print('É um número decimal ?')
print(s.isdecimal())
print('É uma letra em  maiúscula?')
print(s.isupper())
