a = input('Digite algo: ')
print('O tipo primitivo desse valor é:', type(a))
print('Só tem espaços? ', a.isspace())
print('Só tem números? ', a.isnumeric())
print('É alfabetico? ', a.isalpha())
print('É composto por letras e números? ', a.isalnum())
print('Esta em maiusculas? ', a.isupper())
print('Esta em minusculas? ', a.islower())
print('Esta capitalizada?', a.istitle())